title: Neylon Santos
description: Cristão, desenvolvedor, audiofilo, tentando viver a vida de forma minimalista.
url: https://neylonsantos.com
baseurl: "/blog"

author:
  name: Neylon Santos
  email: hello@neylon.dev

permalink: /:year/:month/:day/:title/

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

lang: pt-BR

exclude:
  - Gemfile
  - Gemfile.lock
  - vendor
  - .github
  - package.json
  - package-lock.json
  - node_modules
  - scripts
